### ISSUE TITLE
method get_instruments_list() return strange results

### ISSUE THREAD

**Issue by ferrigno** [oda-hub/dispatcher-app#128]
`disp=DispatcherAPI(url='http://dispatcher.staging.internal.odahub.io')`
`instr_list=disp.get_instruments_list()
for i in instr_list:
    print (i)`

returns:

empty
empty-async
magic
isgri
jemx
osa_fake
antares
spi_acs

I suggest to remove empty empty-async osa_fake

**Comment by volodymyrss** [comment]
indeed importer is also just imported, at which time it executes the importing code:

https://github.com/oda-hub/dispatcher-app/blob/1607306e83b860e3723f03c129bfcc0f5c514ba2/cdci_data_analysis/flask_app/dispatcher_query.py#L45

Config is loaded with `run_osa_cdci_server`, which imports things, so the importing happens after.
It is a bit difficult to guarantee some execution order for code which is executed on import. Due to python's approach to not reloading when not needed.
It may be possible to make it work now, but it will be easy to break in the future.
So systematic approach would be to load with a function, when application starts. 

Alternatively, it is not really necessary to not import it, only avoid reporting in instrument list and validating instrument. This exclusion would need to happen in several places.

But it would be much easier to use env variable for debug.

**Comment by burnout87** [comment]
Probably a dedicated function would be the cleanest approach.

But, We are actually already using an env var: DISPATCHER_DEBUG_MODE

I guess this can be used also for this purposed
