### ISSUE TITLE
let's again consider what we as users and stakeholders want to see in the email 

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/dispatcher-app#131]
in follow-up of #113, seems like @ferrigno  is not happy with the email content.

Can we then actually make a template? It can be a string in config. `yaml` supports multi-line strings.
Jinja2 templating is trivial and integrated with flask.

**Comment by ferrigno** [comment]
This message should be sent at the moment of a query.

Dear <USER NAME>,

you receive this message because you submitted a request to get <ODA PRODUCT> from the service provided by University of Geneva available at the URL <ODA_URL>.

Once products will be ready, you will receive a new email message.

You can  inspect the status of your job using the following link <LINK> or resubmitting the python API query.

In case you have questions or issues you can contact us at <contact_email>

Kind regards,

The ODA team.

**Comment by ferrigno** [comment]
This message should be sent when data are ready.

Dear -USER NAME-,

you receive this message because you submitted a request to get from the service provided by University of Geneva available at the URL <ODA_URL>.

The requested products are <ready/failed> you can retrieve them at the  following link -LINK- or resubmitting the python API query.

In case <your job failed or> you have questions or issues you can contact us at <contact_email>

Kind regards,

The ODA team.

**Comment by ferrigno** [comment]
The subject should be:
[ODA][submitted/ready] Request for-product- created at 2021-05-21 12:42:58 UT

Remove (or label) the final hash, I have no idea what it is.

**Comment by volodymyrss** [comment]
I'd really put the templates in files and later discuss further changes as needed.

**Comment by ferrigno** [comment]
User experience is fundamental and will be improved with use and feedback. Nothing against the strategy of having templates in files, but we cannot release ODA with the current email formatting.

**Comment by burnout87** [comment]
I will provide a first implementation with the proposed format

**Comment by volodymyrss** [comment]
> User experience is fundamental and will be improved with use and feedback. Nothing against the strategy of having templates in files, but we cannot release ODA with the current email formatting.

I am a bit surprised you see this as a blocking issue, since emails are not unreasonable, even if not what would, but ok, let's do that.
