### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'dummy_cache' error happens when config is not ready correctly

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/dispatcher-app#14]
ERROR:cdci_data_analysis.flask_app.dispatcher_query:!!! failed operation: get dataserver products 
ERROR:cdci_data_analysis.flask_app.dispatcher_query:Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/cdci_data_analysis/analysis/queries.py", line 560, in get_query_products
    self.query_prod_list = self.get_dummy_products(instrument,config=config,out_dir=scratch_dir,api=api)
  File "/usr/local/lib/python3.8/site-packages/cdci_osa_plugin/osa_image_query.py", line 197, in get_dummy_products
    dummy_cache = config.dummy_cache
AttributeError: 'NoneType' object has no attribute 'dummy_cache'

**Comment by volodymyrss** [comment]
@dsavchenko also experienced this one

**Comment by burnout87** [comment]
Thoughts after some debugging attempts:

- the server configuration data are supposed to be loaded inside the configurer, but this is not happening because the configuration file loaded (for the tests in my case, but perhaps it is always the same), **_test-conf.yml_**, does not cointain any of this data. Is this normal?
- the configuration of the plugin is not actually loaded anywhere. Have I missed it?

**Comment by volodymyrss** [comment]
> Thoughts after some debugging attempts:
> 
>     * the server configuration data are supposed to be loaded inside the configurer, but this is not happening because the configuration file loaded (for the tests in my case, but perhaps it is always the same), **_test-conf.yml_**, does not cointain any of this data. Is this normal?

I am relatively convinced this is not always the case, since it happens to actually work with parameters provided in the config.

could we maybe add some extra diagnostic output, e.g. also in output of here:  http://in.internal.odahub.io/staging-1-3/dispatcher/run_analysis (secret information excluding, of course)

> 
>     * the configuration of the plugin is not actually loaded anywhere. Have I missed it?

normally, it is loaded here, and it is indeed somehow working as well:

https://github.com/oda-hub/dispatcher-plugin-integral/blob/staging-1.3/cdci_osa_plugin/__init__.py

how it is propagated later - it is not necessarily clear. Could you perhaps add some identifiable output in log (perhaps, error level logging), sentry report if this is encountered, and also this report on the url - so that we can diagnose in live etc.

and also maybe a test.

**Comment by volodymyrss** [comment]
for test, it takes test-conf.yaml in here: https://github.com/oda-hub/dispatcher-app/blob/master/tests/conftest.py#L43
for deployment, it's set similarly: https://github.com/oda-hub/dispatcher-container/blob/master/entrypoint.sh#L9

configs of plugins are set by default similarly to that of dispatcher: https://github.com/oda-hub/dispatcher-plugin-integral/blob/staging-1.3/cdci_osa_plugin/__init__.py#L28
but if not - by variable

as in the deployment:
https://github.com/oda-hub/dispatcher-container/blob/master/Dockerfile#L39

then, they are passed to Instrument constructor as https://github.com/oda-hub/dispatcher-plugin-integral/blob/staging-1.3/cdci_osa_plugin/osa_isgri.py#L100 etc

but it's true that some of the mechanisms meant to set dispatcher plugin config from dispatcher seem to be never used

hope this helps!

**Comment by burnout87** [comment]
Thanks a lot! I understood a lot more!

The plugin configuration (also server configuration?) is indeed loaded at the moment the plugin is initialized, and then for each instrument object initialized, the relative section is read and stored within.

Anyway, I noticed that when loading the configuration within the function _set_config_, at the moment the query is run by the dispatcher, the configuration for the server are searched within the configuration initially loaded (_test-conf.yaml_ configuration file), and therefore not found.

What I did, currently just for testing, was to search for the server configuration within the instrument object.
But don't know if this is actually the best way...

then I couldnt finish properly the test since it search for the _**isgri_query_mosaic.fits**_ file...
