### ISSUE TITLE
Use of catalog for light curve extraction not working or not obvious

### ISSUE THREAD

**Issue by andriineronov** [oda-hub/dispatcher-app#202]
I played with light curve extraction, used catalog from imaging (pressed the button "use catalog" and saw "inline catalog" appearing.... but the results for the light curve include some "NEW" sources and there is no result for my source of interest. Did I do something wrong? (look at the screenshot: incline catalog and results tables are not the same)

<img width="1101" alt="Screenshot 2021-07-03 at 10 24 03" src="https://user-images.githubusercontent.com/27765790/124348196-d5280f00-dbe8-11eb-8bbe-8dec47f10aee.png">

**Comment by volodymyrss** [comment]
> It is clear that the catalog is currently ignored on staging-1.3, because if I do a simple test: submit e.g. spectral extraction without catalog, get the result, then press "use catalog with selected sources" and press again "submit", the system immediately returns the result, as if the request is the same as before (but it is not, because now the catalog is added!).

by the way, not directly related, but we do not anymore call it `staging-1.3` since we maintain now only one staging. See details [there](https://github.com/oda-hub/doc-handbook/#current-strategy). Previously older staging was used off-label, for special features, and that lead to divergence in features between different usable versions.

**Comment by volodymyrss** [comment]
![image](https://user-images.githubusercontent.com/3909535/124974740-7110ab00-e02d-11eb-8ff3-b6d2e120d5a5.png)
seems ok
