### ISSUE TITLE
Avoid token validation for url resolution?

### ISSUE THREAD

**Issue by burnout87** [oda-hub/dispatcher-app#229]

**Comment by burnout87** [comment]
After a discussion with @ferrigno @andriineronov and @motame , we realized it is not strictly necessary to include the token when building the `resolve-job-url` link to include within the email.

The token will be in any case validated by the dispatcher once the request is submitted bu the frontend (which will include the token).

**Comment by burnout87** [comment]
Here it is a possible way to visualize an error message coming from a non valid email link.

It is based on using a dedicated error_message, generated from the dispatcher, and visualized over the frontend.

What do you think?

![image](https://user-images.githubusercontent.com/3757833/131868062-9e9e1625-8af8-46cf-bc32-93f173a8322a.png)

**Comment by volodymyrss** [comment]
> After a discussion with @ferrigno @andriineronov and @motame , we realized it is not necessary to include the token when building the `resolve-job-url` link to include within the email.
> 
> The token will be in any case validated by the dispatcher once the request is submitted bu the frontend (which will include the token).

the problem with removing check is that it has to be revised very carefully, since it is a sensitive point.
but we discussed it in the PR.

token prevents from learning request content based on the session id/job id. This is not too dangerous.

The question is however why is it necessary to remove a safety check which changes nothing?
Token pretty likely to live comparable time to the session id / job id.

**Comment by burnout87** [comment]
Also error status code is displayed

![image](https://user-images.githubusercontent.com/3757833/132491544-2969e4b3-44bc-4992-945c-4b1ec77e2456.png)
