### ISSUE TITLE
'Instrument' object has no attribute 'disp_conf' for icecube

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/dispatcher-app#671]
https://cdci.sentry.io/issues/5248797826/?project=1467382&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=24h&stream_index=1

maybe this is for plugin

**Comment by volodymyrss** [comment]
note that the request was that of @burnout87, 1e3d9aa6d627e92c

**Comment by burnout87** [comment]
made the inspection and the job is indeed failed, and the email for submitted, and done (finished with empty [products) are sent 

the time where the `disp_conf` is set is (only) here:

https://github.com/oda-hub/dispatcher-app/blob/8d519bf453c42443e22cb5dadcbf24a71e49d706/cdci_data_analysis/flask_app/dispatcher_query.py#L2167

and the plugin requests (and fails) it here:

https://github.com/oda-hub/dispatcher-plugin-nb2workflow/blob/b2f806d0b539680345ec74793991d0bfb20afd45/dispatcher_plugin_nb2workflow/dataserver_dispatcher.py#L27

**Comment by burnout87** [comment]
The `test_connection` fails

https://github.com/oda-hub/dispatcher-plugin-nb2workflow/blob/b2f806d0b539680345ec74793991d0bfb20afd45/dispatcher_plugin_nb2workflow/dataserver_dispatcher.py#L69-L105

What's the value of `data_server_url` ?

**Comment by burnout87** [comment]
I might have an explanation but I am not 100% sure about it:

in the case we decide to re-submit the request because the `resubmit_timeout` has expired,  I noticed that the `disp_conf` is not set for the instrument object:

https://github.com/oda-hub/dispatcher-app/blob/8d519bf453c42443e22cb5dadcbf24a71e49d706/cdci_data_analysis/flask_app/dispatcher_query.py#L2074-L2131

whereas it is 

here https://github.com/oda-hub/dispatcher-app/blob/8d519bf453c42443e22cb5dadcbf24a71e49d706/cdci_data_analysis/flask_app/dispatcher_query.py#L2167

though it is hard to understand if in this instance there was a re-submission because of the expiration of the timeout

**Comment by burnout87** [comment]
By better analyzing the sentry breadcrumb, this happened during a re-submission. Therefore #675

**Comment by burnout87** [comment]
looks like it happened again

https://cdci.sentry.io/issues/5331323486/?alert_rule_id=723253&alert_timestamp=1715358851584&alert_type=email&environment=production&notification_uuid=ed946a7d-c37e-4ddb-b67e-4685479f6f4a&project=1467382&referrer=alert_email
