### ISSUE TITLE
pypi cdci_data_analysis version is not regularly updated

### ISSUE THREAD

**Issue by ferrigno** [oda-hub/dispatcher-app#703]
If I do 
pip install cdci_data_analysis 
I get an old verison of the dispatcher that is faulty 
e.g. line 55 of analysis/catalog.py contains np.bool that is deprecated, while the source code in the master branch is correct

**Comment by ferrigno** [comment]
pip installed version is 1.3.3, while the current version is 1.3.5

**Comment by volodymyrss** [comment]
Do you need the pip version? Where?

In principle pypi is not regularly updated for dispatcher. And if it was, it would need to be renamed probably.
The dispatcher is integrated in container without relying on pypi.
All user-specific things are moved or are being moved to oda_api.

Note that I will rename the issue since "pip installed" can be anything, not just pypi.
Also it's best if when you identify the issue, you report it as such, with details on what is the issue and what it prevents you from doing. 
There is some information and thanks for that, but not all.

**Comment by ferrigno** [comment]
Use case: I am importing the catalog.py module from the dispatcher in my wrapper to build a catalog from a dictionary. As you suggest, I will add the file to the wrapper.
https://gitlab.astro.unige.ch/oda/api-clients/oda_api_wrapper/-/blob/master/oda_integral_wrapper/wrapper.py?ref_type=heads#L739

I imported the dispatcher following a suggestion of yours for my  specialized notebooks
https://gitlab.renkulab.io/astronomy/mmoda/isgri-expert/-/blob/main/requirements.txt?ref_type=heads
it should not be anymore necessary if I copy the catalog

**Comment by ferrigno** [comment]
Closing as not relevant
